### ISSUE TITLE
used to work doesn't now

### ISSUE THREAD

**Issue by HMLKintyre** [mobeets/pdf-page-orderer#2]
ERROR reading pdf: name 'file' is not defined

**Comment by mobeets** [comment]
Thanks for letting me know—it should be working now!

**Comment by mobeets** [comment]
If not, please let me know

**Comment by HMLKintyre** [comment]
Brilliant, it works again. Thanks for fixing it - such a useful little programme.

**Comment by mobeets** [comment]
Great, I'm glad it's helpful!
